// Auto-detect Android SDK and write local.properties for the current machine.
// This is needed because this project is synced via cloud storage across multiple
// computers, each with different usernames/SDK paths.
fun findAndroidSdk(): String? {
    // 1. Check environment variables first
    System.getenv("ANDROID_HOME")?.let { if (File(it).exists()) return it }
    System.getenv("ANDROID_SDK_ROOT")?.let { if (File(it).exists()) return it }

    // 2. Check common default locations
    val userHome = System.getProperty("user.home")
    val os = System.getProperty("os.name").lowercase()
    val candidates = when {
        os.contains("win") -> listOf(
            "$userHome/AppData/Local/Android/Sdk",
            "C:/Android/Sdk"
        )
        os.contains("mac") -> listOf(
            "$userHome/Library/Android/sdk"
        )
        else -> listOf( // Linux
            "$userHome/Android/Sdk",
            "/opt/android-sdk"
        )
    }
    return candidates.firstOrNull { File(it).exists() }
}

findAndroidSdk()?.let { sdkPath ->
    val localPropsFile = File(rootDir, "local.properties")
    // Normalize to forward slashes for the properties file
    val normalizedPath = sdkPath.replace("\\", "/")
    val desiredLine = "sdk.dir=$normalizedPath"

    // Only rewrite if the current value is wrong or missing
    val currentSdkDir = if (localPropsFile.exists()) {
        localPropsFile.readLines().firstOrNull { it.trimStart().startsWith("sdk.dir=") }
    } else null

    // Compare normalized paths
    val currentPath = currentSdkDir?.substringAfter("=")
        ?.replace("\\\\", "/")?.replace("\\:", ":")?.trim()
    if (currentPath != normalizedPath) {
        localPropsFile.writeText(
            "# Auto-generated by settings.gradle.kts — do not edit manually.\n" +
            "# This file is regenerated on each build to match the current machine's SDK location.\n" +
            "$desiredLine\n"
        )
        println(">> local.properties updated: sdk.dir=$normalizedPath")
    }
}

pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
        maven { url = uri("https://jitpack.io") }
    }
}
plugins {
    id("org.gradle.toolchains.foojay-resolver-convention") version "1.0.0"
}
dependencyResolutionManagement {
    repositories {
        google()
        mavenCentral()
        maven { url = uri("https://jitpack.io") }
    }
}

rootProject.name = "My Application"
include(":app")
